version: "3.8"
services:
  devcontainer:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      EXAMPLE: "EXAMPLE"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
